### ISSUE TITLE
Is there a way to print stacktraces when they are included in a special field instead of the message field?

### ISSUE THREAD

**Issue by mrsarm** [brocode/fblog#101]
Awesome CLI, it's on my toolbox starting Today !

It's common to have JSON logs with stacktraces, backtraces, trackbacks... or whatever is called depending of the platform used, but recorded in a special field instead of built in in the "message" field with a breaking line separating it (`\n`). Here is an example:

```json
{"filename": "utils.py", "lineno": 107, "message": "Task 6795187211520589 FAILED.", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/myapp/tasks/utils.py\", line 53, in retry_handler\n    yield\n  File \"/usr/local/lib/python3.10/site-packages/myapp/tasks/reports.py\", line 45, in prepare_task\n    if task.status == 'PENDING':\nAttributeError: 'Task' object has no attribute 'status'", "timestamp": "2024-08-30T22:28:08.275676Z", "level": "ERROR", "funcName": "callback"}
```

`fblog` prints this (timestamp, level and message):

```
2024-08-30T22:28:08 ERROR: Task 6795187211520589 FAILED.
```

But not the stacktrace because it's in a different field. I would expect something like:

```
2024-08-30T22:28:08 ERROR: Task 6795187211520589 FAILED.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/myapp/tasks/utils.py", line 53, in retry_handler
    yield
  File "/usr/local/lib/python3.10/site-packages/myapp/tasks/reports.py", line 45, in prepare_task
    if task.status == 'PENDING':
AttributeError: 'Task' object has no attribute 'status'
```

Even better if all the tracebacks can be shifted to the right a bit, to better read them, and not confuse them with normal message lines:

```
2024-08-30T22:28:08 ERROR: Task 6795187211520589 FAILED.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/myapp/tasks/utils.py", line 53, in retry_handler
        yield
      File "/usr/local/lib/python3.10/site-packages/myapp/tasks/reports.py", line 45, in prepare_task
        if task.status == 'PENDING':
    AttributeError: 'Task' object has no attribute 'status'
```

Is it possible through a special argument or changing maybe the name of the field?

**Comment by mrsarm** [comment]
Ok, so checking a bit more the README, I've achieved what I wanted doing the following:

1. Create the fblog configuration file at `$HOME/.config/fblog.toml` using the reference file [default_config.toml](https://github.com/brocode/fblog/blob/master/default_config.toml) as a model.
2. Edit the `main_line_format` variable, addding at the end the following:
   ```
   {{#if exc_info}}\n{{exc_info}}{{/if}}
   ```
   So the full line is:
   ```toml
   main_line_format = "{{bold(fixed_size 19 fblog_timestamp)}} {{level_style (uppercase (fixed_size 5 fblog_level))}}:{{#if fblog_prefix}} {{bold(cyan fblog_prefix)}}{{/if}} {{fblog_message}}{{#if exc_info}}\n{{exc_info}}{{/if}}"
   ```

That's it.

So the only question before closing the question would be: is it the best way? is anyway I can make fblog to detect what is the name of the field? because right now at my current work we use like 3 different platforms for development, each one call the name of the stacktrace field differently, and the name can also vary depending of the framework. I can make it work adding more `{{#if FIELDNAME}}\n{{FIELDNAME}}{{/if}}`, just wondering whether there is a better way.

**Comment by bomgar** [comment]
If you actually want to change the main_line this is the way. But I assume want the cli args `-a <fieldname>` or `-d`. Check

**Comment by mrsarm** [comment]
Great, yes, it good to have these options in the CLI as well, because you can make more complex, fine tune parsers and put them into a script, so you don't have to type them each time, but the are no limits, and it's easy to use. Thanks !
