### ISSUE TITLE
thread 'main' panicked at 'Expect to be able to write to out stream.'

### ISSUE THREAD

**Issue by mgmgwi** [brocode/fblog#12]
Sorry to bother you again. This happens when you pipe to less and then quit, like so (bash):

```
> fblog -d huge-log.json | less -r
# now press `:q` to quit less
thread 'main' panicked at 'Expect to be able to write to out stream.: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/log.rs:100:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I don't think that it's a problem, but it doesn't look nice.

**Comment by bomgar** [comment]
Ok a "nicer" error message should be easy

**Comment by bomgar** [comment]
What do you think it should do? I would still write the broken pipe message but easier to read.

**Comment by mgmgwi** [comment]
> What do you think it should do? I would still write the broken pipe message but easier to read.

I think, doing what I did, is a valid use case, so in my opinion there should be no error at all. But this is just me ...

**Comment by bomgar** [comment]
`fblog` has no idea why the output pipe is broken. It should terminate with an exit code. And silently stop working is strange.

**Comment by bomgar** [comment]
@mriehl pointed out that `yes` handles this silently. But this is the obvious use case for `yes`. Maybe this is also the case for `fblog`. But I'm not convinced yet.

**Comment by mgmgwi** [comment]
Is it possible to handle this silently only if fblog is currently writing to StdOut?

**Comment by bomgar** [comment]
`fblog` always writes to stdout. Maybe it should just `exit(0)`. I'm not sure at the moment.

**Comment by mgmgwi** [comment]
But if stdout gets seriously broken, then your error message would be gone too. A non zero exit code would be fine though.

**Comment by bomgar** [comment]
Ok only the exit code is probably the best option. It only propagates if `set -o pipefail` is on.

I think a bit about this before I merge it.

**Comment by bomgar** [comment]
Ok 2.0.1 should no longer have that problem
