### ISSUE TITLE
Support nested fields

### ISSUE THREAD

**Issue by bomgar** [brocode/fblog#17]
Currently only toplevel keys are processed.

**Comment by bomgar** [comment]
Related to https://github.com/brocode/fblog/issues/16

**Comment by bomgar** [comment]
This should probably be done for the filter logic as well. That would also mean to parse numbers as numbers instead of strings.

**Comment by Miuler** [comment]
Please, add support for nested fields, even if I convert it to string it would be fine

**Comment by bomgar** [comment]
This has been open for so long. I will have a look at it on the weekend.
@Miuler what would you expect how the cli arguments should look like? Especially with 
```
{"a": {"b": 1}, "a.b": "1"}
```
Because i thought of `a.b` but in this case I need something extra.

**Comment by bomgar** [comment]
released

**Comment by bomgar** [comment]
Ok needed to more releases for some bugfixing. But not it should work
