### ISSUE TITLE
pretty printed json seems to be an issue

### ISSUE THREAD

**Issue by sassman** [brocode/fblog#31]
I have a json file that I have to pre-process via `jq` after that run I end up in pretty printed (multiline) json. 
Feeding this into fblog causes some strange errors, example below:

the json fed into fblog looks like (excerpt):
```
{
  "@message": "[object Object]\nResponse Headers have already been sent",
  "@timestamp": "2021-05-05T11:00:42.627Z",
  "@fields": {
    "level": "error"
  }
}
{
  "@message": "[object Object]\nResponse Headers have already been sent",
  "@timestamp": "2021-05-05T11:01:13.650Z",
  "@fields": {
    "level": "error"
  }
}
```

This very json ends up like this:

```
$ cat *json* | grep -v 'info' | grep -v 'debug' | jq '.log | fromjson ' | fblog

??? > {
??? >   "@message": "[object Object]\nResponse Headers have already been sent",
??? >   "@timestamp": "2021-05-05T11:00:42.627Z",
??? >   "@fields": {
??? >     "level": "error"
??? >   }
??? > }
??? > {
??? >   "@message": "[object Object]\nResponse Headers have already been sent",
??? >   "@timestamp": "2021-05-05T11:01:13.650Z",
??? >   "@fields": {
??? >     "level": "error"
??? >   }
??? > }
```

besides the json keys not fitting the default of fblog (that can be fixed via `-l | -m | -t`) the whole multiline json topic seems to be the root cause. 

Does fblog expect single line json?

**Comment by bomgar** [comment]
Yes `fblog` currently expects single line json. I didn't expect a log file to be pretty printed.

**Comment by sassman** [comment]
I See, what a pity. But a absolute understandable assumption.

I'll try to condense it then via jq too.

Thanks for the speedy feedback.

**Comment by bomgar** [comment]
Shouldn't you be able to disable pretty print with `jq`? `-c` or so?

**Comment by sassman** [comment]
Yeah works all good. Thanks.
