### ISSUE TITLE
support log tailing

### ISSUE THREAD

**Issue by grinapo** [brocode/fblog#46]
Please
- support tailing logs (reading forever)
- support starting from the end (for tailing)

**Comment by bomgar** [comment]
You should be able to do this with  `tail -f file  | fblog`

**Comment by bomgar** [comment]
@grinapo Is this working for you?

**Comment by grinapo** [comment]
Checking.

**Comment by grinapo** [comment]
Yes, it is working, maybe you could mention it in the readme (as an example, for example).
Thank you!

**Comment by bomgar** [comment]
I added it to the documentation.
