### ISSUE TITLE
"fblog -a" not allow multipy params

### ISSUE THREAD

**Issue by goDeni** [brocode/fblog#6]
![image](https://user-images.githubusercontent.com/28958327/75009136-b74a8600-549b-11ea-9509-9f5aefd15b65.png)

Version: fblog 1.3.1

Good application, but this feature doesn't work on multiple values

Maybe i do something wrong or this is a bug?

**Comment by bomgar** [comment]
It has to be `fblog -a level -a msg sample.json.log` otherwise it would be ambiguous.

**Comment by goDeni** [comment]
Thanks!
