### ISSUE TITLE
RFE: Customizable core fields & layout

### ISSUE THREAD

**Issue by cykl** [brocode/fblog#9]
I like the idea that for each log event fblog displays a _main_ line and optional additional lines per field. However, succinctness is also a virtue. Three lines to display message + logger name + thread name is a significant waste of vertical space. Thus, I had like to be able to cram more info into the main line. 

jaslog, a similar project, includes logger and thread name, https://github.com/jbruggem/jaslog/blob/master/src/line_formats.rs#L76. It seems a reasonable decision, but I imagine that essential fields are context dependent and every user has its personal opinion about what to display in the main line.

Would it make sense to:

 1. Add more fields to the main line
 2. Provide a configuration mechanism to decide what, and perhaps how, to display in the main line

**Comment by bomgar** [comment]
Currently fblog uses command line args like `--message-key` to customize what fields are detected as a message. But I'm not really happy with the current solution. 

A configuration file for all those things is probably a good idea (as long as it is optional). This would also mean the current command line args to customize behavior should be removed.

Then we could use a "pattern" for the main line.

**Comment by mgmgwi** [comment]
Hi,
I would really like the feature to have more fields on the main line.

> Currently fblog uses command line args like `--message-key` to customize what fields are detected as a message.

I tried adding multiple -m parameters like:
```
fblog -m service -m message -m reason
```
but that didn't work as expected.

**Comment by bomgar** [comment]
Sorry that was a bit misleading. The `message-key` argument is used to tell fblog what field contains the message (or multiple options, we actually had that case). For example `msg` or something like that. `fblog` will always display the first "message" field it finds.

Providing a pattern to format the "main" output woulb be a great feature. Currently I don't have the time to implement new features. I'm happy to merge pull requests. But maybe in the future I will make the time.

**Comment by mgmgwi** [comment]
Thanks for the quick answer.

Since I do not know how to write Rust, I cannot help with a PR. Maybe a simple workaround/solution would be to use all `message-keys`. For that one would probably "only" have to adapt this code

https://github.com/brocode/fblog/blob/5b8073a3c43fea135cdd94ae6490e49249754934/src/log.rs#L86-L88

**Comment by bomgar** [comment]
https://github.com/brocode/fblog/pull/11 I started working on this. It is a very early stage. The idea is that the user can provide a handlebar template using the cli. Currently it is just an experiment.

**Comment by bomgar** [comment]
Ok i was able to recreate the current output with handlebars:
`{{bold(fixed_size 19 fblog_timestamp)}} {{level_style (uppercase (fixed_size 5 fblog_level))}}:{{bold(color_rgb 138 43 226 fblog_prefix)}} {{fblog_message}}`

**Comment by bomgar** [comment]
@mgmgwi the branch now supports formatting with cli arguments. I did not check error handling but it seems to work. If you have the time could you please check if it works with your usecase?

I'm planning to add some kind of config file for the format. But I haven't decided if a cli argument pointing to a file is the best option or if it should be a file inside `~/.config/fblog`.

**Comment by bomgar** [comment]
Discussion with @mriehl 
Probably the cli args + bash alias is good enough

**Comment by bomgar** [comment]
I merged this to master. If I get no complaints I will release this soon.

**Comment by mgmgwi** [comment]
@bomgar: Thanks for the fix, but I can't get it working:

```
> fblog --help
fblog 2.0.0
Brocode inc <bros@brocode.sh>
json log viewer
[...]

> export FBFORMAT="{{bold(fixed_size 19 fblog_timestamp)}} {{level_style (uppercase (fixed_size 5 fblog_level))}}:{{bold(color_rgb 138 43 226 fblog_prefix)}} {{fblog_message}}"
> echo $FBFORMAT
{{bold(fixed_size 19 fblog_timestamp)}} {{level_style (uppercase (fixed_size 5 fblog_level))}}:{{bold(color_rgb 138 43 226 fblog_prefix)}} {{fblog_message}}

> fblog --main-line-format $FBFORMAT mylog.json
error: Found argument 'fblog_timestamp)}}' which wasn't expected, or isn't valid in this context

USAGE:
    fblog --main-line-format <main-line-format>

For more information try --help
```

Can you give a working example? Thanks again!

**Comment by bomgar** [comment]
```
2020-04-30 10:01:11 phaun@haun-symbiolab ~/development/projects/fblog (ᚴ [master]) 
» export FBFORMAT="{{bold(fixed_size 19 fblog_timestamp)}} {{level_style (uppercase (fixed_size 5 fblog_level))}}:{{bold(color_rgb 138 43 226 fblog_prefix)}} {{fblog_message}}"
2020-04-30 10:02:20 phaun@haun-symbiolab ~/development/projects/fblog (ᚴ [master]) 
» fblog --main-line-format $FBFORMAT sample.json.log                                                                                                                            
??? > test
??? > with prefix and not parsable | {"level
??? > with prefix | {"level":"xyz","msg":"Trust key rsa-43fe6c3d-6242-11e7-8b0c-02420a000007 found in cache","package":"trust","process":"gatekeeper","store":"cache","time":"2017-07-06T15:21:16Z","version":"0.1.20170620v0125"}
??? > with prefix | {"level":"debug","msg":"Trust key rsa-43fe6c3d-6242-11e7-8b0c-02420a000007 found in cache","package":"trust","process":"gatekeeper","store":"cache","time":"2017-07-06T15:21:16Z","version":"0.1.20170620v0125"}
2017-07-06T15:21:16  INFO: Trust key rsa-43fe6c3d-6242-11e7-8b0c-02420a000007 found in cache
2017-07-06T15:21:16  WARN: Content-Type set both in header (application/json) and attached to entity (text/plain; charset=utf-8), ignoring content type from entity. To remove this warning, use Result.as(...) to set the content type, rather than setting the header manually.
2017-07-06T15:21:16  INFO: Request: Success
```

**Comment by bomgar** [comment]
what shell are you using? maybe there is something that needs escaping.

**Comment by bomgar** [comment]
Ah I see. With bash this doesn't work.

**Comment by bomgar** [comment]
Bash example:
```
[phaun@haun-symbiolab fblog]$ export FBFORMAT='{{bold(fixed_size 19 fblog_timestamp)}} {{level_style (uppercase (fixed_size 5 fblog_level))}}:{{bold(color_rgb 138 43 226 fblog_prefix)}} {{fblog_message}}'
[phaun@haun-symbiolab fblog]$ fblog --main-line-format "$FBFORMAT" sample.json.log
??? > test
??? > with prefix and not parsable | {"level
??? > with prefix | {"level":"xyz","msg":"Trust key rsa-43fe6c3d-6242-11e7-8b0c-02420a000007 found in cache","package":"trust","process":"gatekeeper","store":"cache","time":"2017-07-06T15:21:16Z","version":"0.1.20170620v0125"}
??? > with prefix | {"level":"debug","msg":"Trust key rsa-43fe6c3d-6242-11e7-8b0c-02420a000007 found in cache","package":"trust","process":"gatekeeper","store":"cache","time":"2017-07-06T15:21:16Z","version":"0.1.20170620v0125"}
2017-07-06T15:21:16  INFO: Trust key rsa-43fe6c3d-6242-11e7-8b0c-02420a000007 found in cache
2017-07-06T15:21:16  WARN: Content-Type set both in header (application/json) and attached to entity (text/plain; charset=utf-8), ignoring content type from entity. To remove this warning, use Result.as(...) to set the content type, rather than setting the header manually.
2017-07-06T15:21:16  INFO: Request: Success
```

**Comment by mgmgwi** [comment]
> Bash example:

:-) - that one worked - thanks!

**Comment by cykl** [comment]
> If you have the time could you please check if it works with your usecase?

I just tried latest rev, it seems to do what I was looking for :+1:

>  Probably the cli args + bash alias is good enough

A configuration file can always be added later if aliases are too cumbersome.

Thanks for the patch :100:
