### ISSUE TITLE
Missing pod name prefix

### ISSUE THREAD

**Issue by sondrelg** [brocode/fblog#97]
Hi!

Thanks for creating this! I've been using it daily for a few weeks, and it's great 🥇 

Just noticed the [prefix-logs](https://github.com/brocode/fblog?tab=readme-ov-file#prefix-logs) section in the readme mention that fblog should prefix logs with pod names when multiple pods are queries for logs. Unfortunately, it doesn't seem to work for me:

When I run
```
kubectl logs -l app=foo -n bar --follow | ./target/release/fblog -p
```
with and without `-p`, it prints regular logs with no pod identifier prefix. Am I missing something, or is the readme not quite right?

**Comment by bomgar** [comment]
`-p` does not add the prefix but parses it if it is before the json.

```
with prefix | {"level":"debug","msg":"Trust key rsa-43fe6c3d-6242-11e7-8b0c-02420a000007 found in cache","package":"trust","process":"gatekeeper","store":"cache","time":"2017-07-06T15:21:16Z","version":"0.1.20170620v0125"}

```

Is rendered like this:
```
2017-07-06T15:21:16 DEBUG: with prefix | Trust key rsa-43fe6c3d-6242-11e7-8b0c-02420a000007 found in cache
```

**Comment by bomgar** [comment]
docker-compose for example produces an output like this.

**Comment by bomgar** [comment]
If you want multiple pods you could use this:
`stern -n master --tail 100  . | fblog -p`

https://github.com/rancher/stern

**Comment by sondrelg** [comment]
Cool, thanks for getting back to me!
