### ISSUE TITLE
[feature request] Excluded values in config

### ISSUE THREAD

**Issue by samuel-deal-tisseo** [brocode/fblog#99]
Hello

Fblog is a great tool ! Thank you for your work.

It would be great if we can exclude values using the config files.
Alternatively, a flag to dump all vars except the one already displayed (message, log level....) could be useful.

**Comment by bomgar** [comment]
@samuel-deal-tisseo released 4.11.0

**Comment by samuel-deal-tisseo** [comment]
@bomgar: Thank you !!
